### github-action-variable-04.yml

name: Test Github Actions variable-04
on:
  workflow_dispatch:
    inputs:
      name:
        description: '이름'
        required: true
        default: 'INPUT'
        

jobs:
  inputs_data:
    runs-on: ubuntu-latest
    steps:
      - name: Print input data
	      run: echo "Hello, ${{ inputs.name }}"
